cloud:
  aws:
    credentials:
      accessKey: AKIAQM2LRVP5KIGB3MCR
      secretKey: 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
    s3:
      bucket: ksychat-bucket
    region:
      static: ap-northeast-1
    stack:
      auto: false


