server:
  port: 56000

spring:
  application:
    name: classroom-service
  jpa:
    show-sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/noticedb
    hikari:
      username: root
      password: 1357




eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://10.10.20.36:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    ip-address: 10.10.20.36

    hostname: 10.10.20.36