server:
  port: 56000

spring:
  application:
    name: classroom-service
  jpa:
    show-sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/noticedb
    hikari:
      username: root
      password: 1357
