server:
  port: 19000

spring:
  application:
    name: admin-service

  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: update
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/chat?
    hikari:
      username: root
      password: mariadb


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #      defaultZone: http://192.168.201.108:8761/eureka
      defaultZone: http://10.10.20.95:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    ip-address: 10.10.20.95

    hostname: 10.10.20.95
