server:
  port: 8000


spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
     globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://35.82.227.83:3000"
              - "http://35.112.12.39:3000"
              - "http://3.142.173.27:3000"
              - "http://ec2-3-142-173-27.us-east-2.compute.amazonaws.com:3000"
            allowCredentials: true
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE
     routes:
        - id: notice
          uri: lb://NOTICE
          predicates:
            - Path=/notice/**
            - Method=GET, POST, DELETE, PUT
          filters:
            - RewritePath=/notice/(?<segment>.*), /$\{segment}




eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh, info